version: "3.2"
services:
  phone-booking:
    image: phone-booking:latest
    container_name: phonebooking-container
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/phone
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
      image: gcr.io/google-containers/cadvisor:latest
      container_name: cadvisor
      ports:
        - '8084:8080'
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
