server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phone
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.ddl-auto: update

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true